name: Create draft release from CHANGELOG.md

on:
  push:
    paths:
      - 'CHANGELOG.md'

jobs:
  update-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create draft release if needed
        uses: apivideo/api.video-release-from-changelog-action@main
        with:
          github-auth-token: ${{ secrets.GITHUB_TOKEN }}
          prefix: v

